import logging
from uuid import uuid4

from domain.orders.models.Order import Order
from domain.orders.events.OrderPlacedEvent import OrderPlacedEvent as InternalOrderPlacedEvent
from domain.orders.repositories.IOrderWriteRepository import IOrderWriteRepository
from domain.core.events.DomainEventDispatcher import DomainEventDispatcher
from infrastructure.orders.events.OrderIntegrationPublisher import OrderIntegrationEventPublisher
from .PlaceOrderCommand import PlaceOrderCommand

logger = logging.getLogger(__name__)


class PlaceOrderHandler:
    def __init__(
        self,
        write_repository: IOrderWriteRepository,
        domain_event_dispatcher: DomainEventDispatcher,
        integration_event_publisher: OrderIntegrationEventPublisher
    ):
        self._repository = write_repository
        self._domain_event_dispatcher = domain_event_dispatcher
        self._integration_event_publisher = integration_event_publisher

    async def handle(self, command: PlaceOrderCommand) -> Order:
        logger.info(f"[PlaceOrderHandler] Processing PlaceOrderCommand for customer {command.customer_id}")
        
        order_id = uuid4()
        order = Order.create(
            id=order_id,
            customer_id=command.customer_id,
            items=command.items
        )
        logger.debug(f"[PlaceOrderHandler] Order aggregate created with ID: {order.id}")
        logger.debug(f"[PlaceOrderHandler] Internal domain events generated by aggregate: {[ev.__class__.__name__ for ev in order.domain_events]}")

        await self._repository.save(order)
        logger.info(f"[PlaceOrderHandler] Order {order.id} saved to write repository.")

        for internal_event in order.domain_events:
            logger.debug(f"[PlaceOrderHandler] Dispatching internal event: {internal_event.__class__.__name__}")
            await self._domain_event_dispatcher.dispatch(internal_event)

        for internal_event in order.domain_events:
            if isinstance(internal_event, InternalOrderPlacedEvent):
                logger.info(f"[PlaceOrderHandler] Publishing InternalOrderPlacedEvent as a public contract for order {order.id}.")
                await self._integration_event_publisher.publish(internal_event)

        order.clear_domain_events()
        logger.debug(f"[PlaceOrderHandler] Domain events cleared from order {order.id}.")

        return order
