import logging

from domain.core.value_objects.EntityId import EntityId
from domain.orders.models.Order import Order
from domain.orders.events.OrderPlacedEvent import OrderPlacedEvent
from domain.orders.repositories.IOrderWriteRepository import IOrderWriteRepository
from domain.core.events.DomainEventDispatcher import DomainEventDispatcher
from infrastructure.orders.events.OrderIntegrationPublisher import OrderIntegrationEventPublisher
from .PlaceOrderCommand import PlaceOrderCommand

logger = logging.getLogger(__name__)


class PlaceOrderHandler:
    integration_events = [OrderPlacedEvent]

    def __init__(
        self,
        write_repository: IOrderWriteRepository,
        domain_event_dispatcher: DomainEventDispatcher,
        integration_event_publisher: OrderIntegrationEventPublisher
    ):
        self._repository = write_repository
        self._domain_event_dispatcher = domain_event_dispatcher
        self._integration_event_publisher = integration_event_publisher

    async def handle(self, command: PlaceOrderCommand) -> Order:
        logger.info(f"[PlaceOrderHandler] Processing PlaceOrderCommand for customer {command.customer_id}")
        
        # Convert customer_id string to EntityId
        customer_entity_id = EntityId.from_string(command.customer_id)
        
        # Convert OrderItemRequest DTOs to the format expected by Order.create()
        items_data_list = [item_model.model_dump() for item_model in command.items]
            
        shipping_details_dict = command.shipping_details.model_dump()

        order = Order.create(
            customer_id=customer_entity_id,
            items_data=items_data_list,
            shipping_details_data=shipping_details_dict,
            currency=command.currency, # PlaceOrderCommand now has these fields with defaults
            shipping_cost_raw=command.shipping_cost_raw,
            tax_amount_raw=command.tax_amount_raw,
            notes=command.notes
        )
        logger.debug(f"[PlaceOrderHandler] Order aggregate created with ID: {order.id}")
        logger.debug(f"[PlaceOrderHandler] Internal domain events generated by aggregate: {[ev.__class__.__name__ for ev in order.domain_events]}")

        await self._repository.save(order)
        logger.info(f"[PlaceOrderHandler] Order {order.id} saved to write repository.")

        # Dispatch all domain events using the new method
        await self._domain_event_dispatcher.dispatch_events(order.domain_events)
        logger.info(f"[PlaceOrderHandler] Dispatched {len(order.domain_events)} domain events for order {order.id}.")

        # Publish integration events for specific internal events
        for internal_event in order.domain_events:
            if internal_event.__class__ in self.integration_events:
                logger.info(f"[PlaceOrderHandler] Publishing {internal_event.__class__.__name__} as a public contract for order {order.id}.")
                await self._integration_event_publisher.publish(internal_event)

        order.clear_domain_events()
        logger.debug(f"[PlaceOrderHandler] Domain events cleared from order {order.id}.")

        return order
